# 1.2.1

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3

In [3]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004558216517166369 0.995421547884299 0.5121313967574171


# 1.2.4

In [4]:
A = np.arange(25).reshape(5, 5)
# A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

# 1.2.6

In [5]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1

In [6]:
import numpy as np
A = np.zeros((8,8))
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 1.3.2

In [8]:
import numpy as np
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 1.3.3

In [9]:
import numpy as np
A = np.random.random((3,3,3))
print(A)

[[[0.37750008 0.35794695 0.00713448]
  [0.45442023 0.77338642 0.52693161]
  [0.39411936 0.24971623 0.43227794]]

 [[0.60931313 0.37868531 0.6831074 ]
  [0.0883631  0.28037283 0.68484162]
  [0.65661925 0.9048099  0.27949394]]

 [[0.30409659 0.05461041 0.43812863]
  [0.22580616 0.56475274 0.59271565]
  [0.42850029 0.66210218 0.72805504]]]


# 1.3.4

In [10]:
import numpy as np
A = np.ones((3,3))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


# 1.3.5

In [11]:
arr = np.arange(10,20)
arr.sort()
print(arr)
arr=arr[::-1]
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


# 1.3.6

In [12]:
import numpy as np
A = np.arange(25).reshape(5,5)
X = A.ndim
Y = A.size
Z = A.shape
print(A ,"\n","Shape",Z ,"\n","Size", Y,"\n","Dimension",X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 Shape (5, 5) 
 Size 25 
 Dimension 2


# 2.2.1

In [45]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


# 2.2.2

In [46]:
s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3

In [38]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4

In [39]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5

In [40]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6

In [41]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7

In [42]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1

In [43]:
import math
s = pd.Series([(7, -11), (13, 6)], ['a', 'b'])
e = math.sqrt(pow(s['a'][0]-s['b'][0], 2)+pow(s['a'][1]-s['b'][1], 2))
e

18.027756377319946

# 2.3.2

In [47]:
import pandas as pd
import numpy as np
A ='https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(A)
dataframe.head(10)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0  0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1  0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4  0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   
5  0.238  0.272   53  106  18  3  15   59  22  107  14   7   0   0   0   0   
6  0.115  0.148    0    3   1  0   0    2   1    6   0   3   0   0   0   0   
7  0.307  0.405   98  167  35  1  14   52  84   72   0  15   0   0   0   0   
8  0.187  0.281   38   50   9  2  15   37  32   98   0   9   0   0   0   0   
9  0.266  0.359  115  152  32  1  44  122  78  152  26   9   1   0   0   0   

   salary  
0     109  
1     160  
2    2700  
3     550  
4     300  
5     230  
6     109  
7     560  
8     142  
9    4300

# 2.3.3

In [50]:
import pandas as pd
import numpy as np
A ='https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(A)

dataframe.describe()


1           2           3           4           5           6  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     0.257825    0.323973   46.697329   92.833828   16.673591    2.338279   
std      0.039546    0.047132   29.020166   51.896322   10.452001    2.543336   
min      0.063000    0.063000    0.000000    1.000000    0.000000    0.000000   
25%      0.238000    0.297000   22.000000   51.000000    9.000000    0.000000   
50%      0.260000    0.323000   41.000000   91.000000   15.000000    2.000000   
75%      0.281000    0.354000   69.000000  136.000000   23.000000    3.000000   
max      0.457000    0.486000  133.000000  216.000000   49.000000   15.000000   

                7           8           9          10          11          12  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     9.097923   44.020772   35.017804   56.706231    8.246291    6.771513   
std      9.289934   29.559406   24.842474   33.828784   11.664782    5.927490   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%      2.000000   21.000000   15.000000   31.000000    1.000000    3.000000   
50%      6.000000   39.000000   30.000000   49.000000    4.000000    5.000000   
75%     15.000000   66.000000   49.000000   78.000000   11.000000    9.000000   
max     44.000000  133.000000  138.000000  175.000000   76.000000   31.000000   

               13          14          15          16       salary  
count  337.000000  337.000000  337.000000  337.000000   337.000000  
mean     0.397626    0.115727    0.192878    0.029674  1248.528190  
std      0.490135    0.320373    0.395145    0.169938  1240.013309  
min      0.000000    0.000000    0.000000    0.000000   109.000000  
25%      0.000000    0.000000    0.000000    0.000000   230.000000  
50%      0.000000    0.000000    0.000000    0.000000   740.000000  
75%      1.000000    0.000000    0.000000    0.000000  2150.000000  
max      1.000000    1.000000    1.000000    1.000000  6100.000000

In [51]:
dataframe.head(2)


1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
0  0.271  0.328  74  161  22  6  12  58  49  133  23  17   1   1   0   0   
1  0.264  0.318  24   48   7  0   1  22  15   18   0   7   0   0   0   0   

   salary  
0     109  
1     160

In [52]:
dataframe.tail(3)


1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
334  0.208  0.265  12   35  11  1   0  15  14   30   2   6   0   0   0   0   
335  0.290  0.349  59  141  30  2  16  64  42  102  14   6   1   0   0   0   
336  0.225  0.312  37   64  12  0  17  48  36   80   1   0   1   0   0   0   

     salary  
334     365  
335     990  
336    2167

In [53]:
dataframe.shape


(337, 17)

In [54]:
dataframe.iloc[5:7]

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
5  0.238  0.272  53  106  18  3  15  59  22  107  14   7   0   0   0   0   
6  0.115  0.148   0    3   1  0   0   2   1    6   0   3   0   0   0   0   

   salary  
5     230  
6     109

# 3.2.1

In [55]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2

In [56]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit(x).transform(x)
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

# 3.2.3

In [60]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A','B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2

In [61]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
A = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(A)
dataframe[['sepal_length_cm']]= scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']]= preprocessing.normalize(dataframe[['sepal_width_cm']])
dataframe.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222             1.0              1.4             0.2  setosa
1         0.166667             1.0              1.4             0.2  setosa
2         0.111111             1.0              1.3             0.2  setosa
3         0.083333             1.0              1.5             0.2  setosa
4         0.194444             1.0              1.4             0.2  setosa